"""Synthetic training data for OCR-damaged heading detection.

Contains documents with clean headings AND their OCR-damaged equivalents.
Each document is a list of (text, is_heading) tuples at the line level.

Covers common OCR/PDF extraction artifacts:
1. Full letterspacing: "D E F I N I T I O N S"
2. Partial letterspacing: "SCHED ULE A", "Sect ion 2.1"
3. Inconsistent spacing: "i n vi i te d p a rt i es"
4. Clean headings (for negative training)
5. Body text that happens to be short (false positive candidates)
"""

from __future__ import annotations

# Each document: list of (line_text, is_heading)
# We include blank lines as (text="", is_heading=False)

LABELED_DOCS: list[list[tuple[str, bool]]] = [
    # Doc 1: Legal contract with letterspaced headings
    [
        ("D E F I N I T I O N S", True),
        ("", False),
        ("In this Agreement, the following terms shall have the meanings set forth below:", False),
        ("", False),
        ('"Agreement" means this Master Services Agreement including all schedules and exhibits.', False),
        ('"Effective Date" means the date first written above.', False),
        ('"Services" means the consulting services described in Schedule A.', False),
        ('"Confidential Information" means any non-public information disclosed by either party.', False),
        ("", False),
        ("S C O P E   O F   S E R V I C E S", True),
        ("", False),
        ("The Contractor shall provide to the Company the Services described in Schedule A attached hereto.", False),
        ("The Contractor shall perform the Services in a professional and workmanlike manner consistent with industry standards.", False),
        ("The Company shall provide reasonable access to its facilities and personnel as necessary for the Contractor to perform the Services.", False),
        ("", False),
        ("C O M P E N S A T I O N", True),
        ("", False),
        ("The Company shall pay the Contractor for Services rendered at the rates specified in Schedule B.", False),
        ("Payment shall be made within thirty (30) days of receipt of a proper invoice.", False),
        ("The Contractor shall submit invoices on a monthly basis for Services performed during the preceding calendar month.", False),
        ("All amounts are exclusive of applicable taxes.", False),
        ("", False),
        ("T E R M   A N D   T E R M I N A T I O N", True),
        ("", False),
        ("This Agreement shall commence on the Effective Date and shall continue for a period of twelve (12) months unless earlier terminated.", False),
        ("Either party may terminate this Agreement upon thirty (30) days prior written notice to the other party.", False),
        ("Upon termination, the Contractor shall deliver all work product to the Company.", False),
        ("", False),
        ("C O N F I D E N T I A L I T Y", True),
        ("", False),
        ("Each party agrees to maintain the confidentiality of Confidential Information received from the other party.", False),
        ("This obligation shall survive termination of this Agreement for a period of five (5) years.", False),
    ],

    # Doc 2: Legal contract with partial letterspacing (messier OCR)
    [
        ("MAST ER SERVI CES AGRE EMENT", True),
        ("", False),
        ("This Master Services Agreement is entered into as of January 15, 2024 by and between:", False),
        ("", False),
        ("Acme Corporation, a Delaware corporation with offices at 123 Main Street, Wilmington, DE 19801", False),
        ("and", False),
        ("Beta Solutions LLC, a California limited liability company with offices at 456 Oak Avenue, San Francisco, CA 94102", False),
        ("", False),
        ("RECIT ALS", True),
        ("", False),
        ("WHEREAS, Acme desires to retain Beta to provide certain professional services; and", False),
        ("WHEREAS, Beta has the expertise and resources to provide such services;", False),
        ("NOW, THEREFORE, in consideration of the mutual covenants herein, the parties agree as follows:", False),
        ("", False),
        ("Arti cle 1 Defin itions", True),
        ("", False),
        ("1.1 Agreement means this Master Services Agreement.", False),
        ("1.2 Services means the work described in each Statement of Work.", False),
        ("1.3 Deliverables means the tangible work product produced under a Statement of Work.", False),
        ("", False),
        ("Arti cle 2 Serv ices", True),
        ("", False),
        ("2.1 Beta shall provide the Services as described in each mutually executed Statement of Work.", False),
        ("2.2 Each Statement of Work shall specify the scope, timeline, deliverables, and fees.", False),
        ("2.3 Beta shall assign qualified personnel to perform the Services.", False),
        ("", False),
        ("Arti cle 3 Paym ent", True),
        ("", False),
        ("3.1 Acme shall pay Beta the fees specified in each Statement of Work.", False),
        ("3.2 Invoices shall be submitted monthly and are due net 30.", False),
        ("3.3 Late payments shall bear interest at 1.5% per month.", False),
        ("", False),
        ("SCHED ULE A", True),
        ("", False),
        ("Statement of Work No. 1", False),
        ("Project: Data Migration and Integration Services", False),
        ("Duration: 6 months from the Effective Date", False),
        ("Fee: $150,000 payable in equal monthly installments", False),
    ],

    # Doc 3: Government/regulatory document with mixed clean + OCR headings
    [
        ("R E G U L A T I O N   N O .   2 0 2 3 - 4 5", True),
        ("", False),
        ("CHAPTER I", True),
        ("G E N E R A L   P R O V I S I O N S", True),
        ("", False),
        ("Section 1. This regulation establishes the framework for environmental impact assessment procedures for all federal projects exceeding $10 million in value.", False),
        ("", False),
        ("Section 2. All agencies shall comply with the requirements set forth herein within 180 days of publication.", False),
        ("", False),
        ("CHAPTER II", True),
        ("A S S E S S M E N T   P R O C E D U R E S", True),
        ("", False),
        ("Section 3. Prior to initiating any covered project, the responsible agency shall conduct a preliminary environmental screening.", False),
        ("", False),
        ("The screening shall evaluate potential impacts on air quality, water resources, endangered species habitat, and cultural heritage sites.", False),
        ("", False),
        ("Section 4. If the preliminary screening identifies potential significant impacts, a full Environmental Impact Statement shall be prepared.", False),
        ("", False),
        ("The EIS shall include detailed analysis of alternatives, mitigation measures, and cumulative impacts.", False),
        ("", False),
        ("C H A P T E R   I I I", True),
        ("P U B L I C   P A R T I C I P A T I O N", True),
        ("", False),
        ("Section 5. The agency shall provide public notice of the proposed project and the availability of environmental documents.", False),
        ("", False),
        ("A minimum comment period of 45 days shall be provided for draft Environmental Impact Statements.", False),
        ("All substantive comments received shall be addressed in the final EIS.", False),
    ],

    # Doc 4: Inconsistently spaced OCR (worst case)
    [
        ("i n vi te d p a rt i es", True),
        ("", False),
        ("The following entities have been invited to participate in the joint venture:", False),
        ("Alpha Holdings Ltd, registered in the United Kingdom", False),
        ("Beta Capital Partners, a Cayman Islands limited partnership", False),
        ("Gamma Technologies Inc, incorporated in Singapore", False),
        ("", False),
        ("pro j ect des cri pti on", True),
        ("", False),
        ("The project involves the development of a mixed-use commercial complex on a 12-acre site located in the central business district.", False),
        ("The development will include approximately 500,000 square feet of Class A office space, 200 residential units, and 80,000 square feet of retail.", False),
        ("Construction is expected to commence in Q3 2024 with completion targeted for Q1 2027.", False),
        ("", False),
        ("cap i tal con tri but ions", True),
        ("", False),
        ("Each invited party shall contribute capital in proportion to their ownership interest as follows:", False),
        ("Alpha Holdings: 40% - $80,000,000", False),
        ("Beta Capital: 35% - $70,000,000", False),
        ("Gamma Technologies: 25% - $50,000,000", False),
        ("Total project capitalization: $200,000,000", False),
        ("", False),
        ("g over ni ng l aw", True),
        ("", False),
        ("This agreement shall be governed by and construed in accordance with the laws of the State of New York.", False),
        ("Any disputes arising under this agreement shall be resolved by binding arbitration in New York City.", False),
    ],

    # Doc 5: SEC filing with letterspaced section headers
    [
        ("UNITED STATES SECURITIES AND EXCHANGE COMMISSION", True),
        ("Washington, D.C. 20549", False),
        ("", False),
        ("F O R M   1 0 - K", True),
        ("", False),
        ("Annual Report Pursuant to Section 13 or 15(d) of the Securities Exchange Act of 1934", False),
        ("For the fiscal year ended December 31, 2023", False),
        ("Commission File Number: 001-12345", False),
        ("", False),
        ("P A R T   I", True),
        ("", False),
        ("I t e m   1 .   B u s i n e s s", True),
        ("", False),
        ("The Company is a leading provider of enterprise software solutions serving over 10,000 customers worldwide.", False),
        ("Our products enable organizations to manage their digital transformation initiatives.", False),
        ("Revenue for fiscal year 2023 was $2.3 billion, an increase of 15% from the prior year.", False),
        ("", False),
        ("I t e m   1 A .   R i s k   F a c t o r s", True),
        ("", False),
        ("Investing in our common stock involves significant risks. You should carefully consider the following risk factors.", False),
        ("Our operating results may fluctuate significantly from quarter to quarter.", False),
        ("We face intense competition from both established companies and new entrants.", False),
        ("", False),
        ("I t e m   7 .   M a n a g e m e n t   D i s c u s s i o n", True),
        ("", False),
        ("The following discussion should be read in conjunction with our consolidated financial statements.", False),
        ("Total revenue increased 15% year-over-year driven by strong demand for our cloud platform.", False),
        ("Operating margin expanded 200 basis points to 22% reflecting improved operational efficiency.", False),
        ("", False),
        ("P A R T   I I", True),
        ("", False),
        ("I t e m   8 .   F i n a n c i a l   S t a t e m e n t s", True),
        ("", False),
        ("The consolidated financial statements are included in this Annual Report beginning on page F-1.", False),
    ],

    # Doc 6: Clean document (no OCR damage) — negative examples
    [
        ("MASTER LEASE AGREEMENT", True),
        ("", False),
        ("This Master Lease Agreement is made effective as of March 1, 2024.", False),
        ("", False),
        ("ARTICLE 1 - DEFINITIONS", True),
        ("", False),
        ("1.1 Premises means the office space located at Suite 400, 789 Commerce Boulevard.", False),
        ("1.2 Landlord means Pacific Properties LLC.", False),
        ("1.3 Tenant means CloudTech Solutions Inc.", False),
        ("", False),
        ("ARTICLE 2 - LEASE TERM", True),
        ("", False),
        ("2.1 The initial term of this Lease shall be five (5) years commencing on April 1, 2024.", False),
        ("2.2 Tenant shall have two (2) options to renew for additional three (3) year terms each.", False),
        ("", False),
        ("ARTICLE 3 - RENT", True),
        ("", False),
        ("3.1 Base Rent shall be $45.00 per square foot per annum, payable monthly in advance.", False),
        ("3.2 Rent shall increase by 3% annually on each anniversary of the Commencement Date.", False),
        ("3.3 In addition to Base Rent, Tenant shall pay its proportionate share of operating expenses.", False),
        ("", False),
        ("ARTICLE 4 - USE OF PREMISES", True),
        ("", False),
        ("4.1 Tenant shall use the Premises solely for general office purposes.", False),
        ("4.2 Tenant shall not use the Premises for any unlawful purpose.", False),
        ("4.3 Tenant shall comply with all applicable laws, regulations, and ordinances.", False),
    ],

    # Doc 7: Mixed — some headings OCR damaged, some clean
    [
        ("CONFIDENTIAL SETTLEMENT AGREEMENT", True),
        ("", False),
        ("This Confidential Settlement Agreement is entered into by the undersigned parties to resolve all disputes arising from Case No. 2023-CV-4567.", False),
        ("", False),
        ("B A C K G R O U N D", True),
        ("", False),
        ("On or about June 15, 2022, Plaintiff filed a complaint alleging breach of contract and misappropriation of trade secrets.", False),
        ("Defendant denied all allegations and filed counterclaims for tortious interference.", False),
        ("The parties have engaged in extensive discovery and mediation proceedings.", False),
        ("", False),
        ("SETTLEMENT TERMS", True),
        ("", False),
        ("1. Defendant shall pay Plaintiff the sum of $2,500,000 within 30 days of execution of this Agreement.", False),
        ("2. Payment shall be made by wire transfer to an account designated by Plaintiff.", False),
        ("3. Upon receipt of payment, Plaintiff shall dismiss all claims with prejudice.", False),
        ("", False),
        ("M U T U A L   R E L E A S E S", True),
        ("", False),
        ("Each party hereby releases and forever discharges the other party from any and all claims, demands, and causes of action.", False),
        ("This release extends to all known and unknown claims arising from the subject matter of the litigation.", False),
        ("", False),
        ("NON-DISPARAGEMENT", True),
        ("", False),
        ("Neither party shall make any disparaging statements about the other party.", False),
        ("This provision shall survive termination of this Agreement.", False),
        ("", False),
        ("C O N F I D E N T I A L I T Y", True),
        ("", False),
        ("The terms of this Agreement shall be kept strictly confidential by all parties.", False),
        ("Disclosure is permitted only as required by law or with prior written consent.", False),
    ],

    # Doc 8: Very messy OCR with numbering artifacts
    [
        ("Sect ion 1 Gene ral Prov isi ons", True),
        ("", False),
        ("This policy applies to all employees of the organization regardless of position or tenure.", False),
        ("All employees are expected to familiarize themselves with the contents of this handbook.", False),
        ("", False),
        ("Sect ion 2 Emp loy ment Pol ici es", True),
        ("", False),
        ("2.1 The organization is committed to equal employment opportunity and does not discriminate on any basis prohibited by law.", False),
        ("2.2 All hiring decisions shall be based on qualifications, experience, and merit.", False),
        ("2.3 Background checks will be conducted for all new hires prior to start date.", False),
        ("", False),
        ("Sect ion 3 Com pen sat ion and Bene fi ts", True),
        ("", False),
        ("3.1 Compensation is reviewed annually and adjustments are made based on performance evaluations and market data.", False),
        ("3.2 Full-time employees are eligible for the comprehensive benefits package including medical, dental, and vision insurance.", False),
        ("3.3 The organization matches employee 401(k) contributions up to 6% of base salary.", False),
        ("", False),
        ("Sect ion 4 Con duct and Eth ics", True),
        ("", False),
        ("4.1 All employees shall conduct themselves in a professional manner at all times.", False),
        ("4.2 Conflicts of interest must be disclosed to the compliance officer immediately.", False),
        ("4.3 Violations of this policy may result in disciplinary action up to and including termination.", False),
    ],

    # --- ADVERSARIAL DOCS: short body lines that are NOT headings ---

    # Doc 9: Bullet lists, short items, captions — false positive traps
    [
        ("PURCHASE ORDER TERMS", True),
        ("", False),
        ("The following terms apply to all purchase orders issued by the Company.", False),
        ("", False),
        ("Required documentation:", False),
        ("", False),
        ("- Valid business license", False),
        ("- Certificate of insurance", False),
        ("- W-9 tax form", False),
        ("- Banking information for ACH payments", False),
        ("- Signed non-disclosure agreement", False),
        ("", False),
        ("DELIVERY REQUIREMENTS", True),
        ("", False),
        ("All deliveries must include:", False),
        ("", False),
        ("- Packing slip with PO number", False),
        ("- Material safety data sheets (if applicable)", False),
        ("- Certificate of conformance", False),
        ("", False),
        ("Note: Deliveries without proper documentation will be refused at the dock and returned at supplier's expense.", False),
        ("", False),
        ("Questions? Contact procurement@company.com", False),
        ("", False),
        ("PAYMENT TERMS", True),
        ("", False),
        ("Standard payment terms are Net 60 from date of invoice receipt.", False),
        ("Early payment discount: 2% 10 Net 60.", False),
        ("All invoices must reference the purchase order number.", False),
    ],

    # Doc 10: Signature blocks, page numbers, footers — tricky short lines
    [
        ("EMPLOYMENT AGREEMENT", True),
        ("", False),
        ("This Employment Agreement is entered into effective as of the date last signed below.", False),
        ("", False),
        ("The Employee shall serve as Vice President of Engineering.", False),
        ("Base salary: $275,000 per annum.", False),
        ("Start date: April 1, 2024.", False),
        ("Reporting to: Chief Technology Officer.", False),
        ("", False),
        ("N O N - C O M P E T E", True),
        ("", False),
        ("For a period of twelve months following termination, Employee shall not directly or indirectly engage in any business that competes with the Company within the United States.", False),
        ("", False),
        ("IN WITNESS WHEREOF, the parties have executed this Agreement.", False),
        ("", False),
        ("EMPLOYER:", False),
        ("", False),
        ("By: ___________________________", False),
        ("Name: John Smith", False),
        ("Title: Chief Executive Officer", False),
        ("Date: _______________", False),
        ("", False),
        ("EMPLOYEE:", False),
        ("", False),
        ("By: ___________________________", False),
        ("Name: Jane Doe", False),
        ("Date: _______________", False),
        ("", False),
        ("Page 1 of 3", False),
        ("", False),
        ("S E V E R A B I L I T Y", True),
        ("", False),
        ("If any provision of this Agreement is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.", False),
        ("The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable.", False),
    ],

    # Doc 11: Table-like data, short numeric lines, figure captions
    [
        ("Q U A R T E R L Y   R E P O R T", True),
        ("", False),
        ("For the quarter ended September 30, 2023, we report the following consolidated financial results.", False),
        ("", False),
        ("Revenue: $45.2M", False),
        ("Cost of goods sold: $28.1M", False),
        ("Gross profit: $17.1M", False),
        ("Operating expenses: $12.3M", False),
        ("Net income: $4.8M", False),
        ("", False),
        ("Figure 1: Revenue by segment", False),
        ("(see attached chart)", False),
        ("", False),
        ("S E G M E N T   A N A L Y S I S", True),
        ("", False),
        ("Enterprise segment revenue grew 22% year-over-year driven by large deal closures in the financial services vertical.", False),
        ("SMB segment revenue declined 3% reflecting increased churn in the bottom quartile of accounts.", False),
        ("", False),
        ("Source: Internal financial records", False),
        ("Prepared by: Finance Department", False),
        ("Date: October 15, 2023", False),
        ("", False),
        ("O U T L O O K", True),
        ("", False),
        ("Management expects full-year revenue to be in the range of $180M to $185M, representing growth of 18% to 21% over the prior fiscal year.", False),
        ("Capital expenditures are expected to be approximately $15M for the full year as we invest in data center expansion.", False),
        ("", False),
        ("* Forward-looking statements subject to risks and uncertainties", False),
        ("** Non-GAAP measure; see reconciliation in appendix", False),
    ],

    # Doc 12: Email-style doc with short greetings, sign-offs (non-headings)
    [
        ("R E :   P R O J E C T   U P D A T E", True),
        ("", False),
        ("Dear Board Members,", False),
        ("", False),
        ("Please find below the monthly status update for Project Phoenix.", False),
        ("", False),
        ("M I L E S T O N E S", True),
        ("", False),
        ("Phase 1 (Data Migration) was completed on schedule with no critical issues.", False),
        ("Phase 2 (Integration Testing) is currently 80% complete and tracking ahead of plan.", False),
        ("Phase 3 (User Acceptance Testing) is scheduled to begin next month.", False),
        ("", False),
        ("Key risks:", False),
        ("", False),
        ("1. Vendor API stability", False),
        ("2. Resource availability in Q4", False),
        ("3. Regulatory approval timeline", False),
        ("", False),
        ("R E C O M M E N D A T I O N S", True),
        ("", False),
        ("We recommend proceeding with the current timeline while maintaining the contingency budget allocation of $500K.", False),
        ("A detailed risk mitigation plan is attached as Appendix A.", False),
        ("", False),
        ("Best regards,", False),
        ("", False),
        ("Sarah Chen", False),
        ("Program Director", False),
        ("", False),
        ("Cc: Legal, Finance, Operations", False),
    ],
]


def get_labeled_lines() -> list[tuple[str, bool]]:
    """Flatten all docs to (line_text, is_heading) pairs, excluding blank lines."""
    result = []
    for doc in LABELED_DOCS:
        for line_text, is_heading in doc:
            if line_text.strip():
                result.append((line_text, is_heading))
    return result


def get_docs_as_text_and_labels() -> list[tuple[str, list[int]]]:
    """Return each doc as (full_text, [heading_line_numbers]).

    Heading line numbers are 0-based indices into the full text's lines.
    """
    result = []
    for doc in LABELED_DOCS:
        lines = [text for text, _ in doc]
        full_text = "\n".join(lines)
        heading_indices = [
            i for i, (text, is_heading) in enumerate(doc)
            if is_heading and text.strip()
        ]
        result.append((full_text, heading_indices))
    return result
